{{- if not .Values.existingSecret.name -}}
{{- $_ := required "config.agentKey is required when existingSecret.name is not set" .Values.config.agentKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acornops-agent.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acornops-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  agent-key: {{ .Values.config.agentKey | quote }}
{{- end }}
